// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: 'AIzaSyDKiepSCtehKmSxt83VTgBltv4Zb8BrE20',
      appId: '1:1075984251330:web:d7118ade70f96d11d47e5b',
      messagingSenderId: '1075984251330',
      projectId: 'smart-home-icet-project',
      authDomain: 'smart-home-icet-project.firebaseapp.com',
      storageBucket: 'smart-home-icet-project.firebasestorage.app',
      measurementId: 'G-S08MLPLNWW',
      databaseURL: 'https://smart-home-icet-project-default-rtdb.firebaseio.com');

  static const FirebaseOptions android = FirebaseOptions(
      apiKey: 'AIzaSyAVdYiQsBmU6MWgELPFtnHu2zFZEPhU2jQ',
      appId: '1:1075984251330:android:2ae71d27fc953442d47e5b',
      messagingSenderId: '1075984251330',
      projectId: 'smart-home-icet-project',
      storageBucket: 'smart-home-icet-project.firebasestorage.app',
      databaseURL: 'https://smart-home-icet-project-default-rtdb.firebaseio.com');

  static const FirebaseOptions ios = FirebaseOptions(
      apiKey: 'AIzaSyDxqXWY6yqwkTAJ37cnpGihgWj8hW0vDzA',
      appId: '1:1075984251330:ios:e30ef2512b4004a0d47e5b',
      messagingSenderId: '1075984251330',
      projectId: 'smart-home-icet-project',
      storageBucket: 'smart-home-icet-project.firebasestorage.app',
      iosBundleId: 'edu.icet.iotProject',
      databaseURL: 'https://smart-home-icet-project-default-rtdb.firebaseio.com');

  static const FirebaseOptions macos = FirebaseOptions(
      apiKey: 'AIzaSyDxqXWY6yqwkTAJ37cnpGihgWj8hW0vDzA',
      appId: '1:1075984251330:ios:e30ef2512b4004a0d47e5b',
      messagingSenderId: '1075984251330',
      projectId: 'smart-home-icet-project',
      storageBucket: 'smart-home-icet-project.firebasestorage.app',
      iosBundleId: 'edu.icet.iotProject',
      databaseURL: 'https://smart-home-icet-project-default-rtdb.firebaseio.com');

  static const FirebaseOptions windows = FirebaseOptions(
      apiKey: 'AIzaSyDKiepSCtehKmSxt83VTgBltv4Zb8BrE20',
      appId: '1:1075984251330:web:3e35e927949718a4d47e5b',
      messagingSenderId: '1075984251330',
      projectId: 'smart-home-icet-project',
      authDomain: 'smart-home-icet-project.firebaseapp.com',
      storageBucket: 'smart-home-icet-project.firebasestorage.app',
      measurementId: 'G-2K68SGQ1T8',
      databaseURL: 'https://smart-home-icet-project-default-rtdb.firebaseio.com');
}
